# Corrected DetectionEvent creation code
# Generated by fix_detection_events_schema_mismatch.py

# Replace the DetectionEvent creation in test_execution_service.py with:
for detection in validated_detections:
                            detection_event = DetectionEvent(
                                id=detection.detection_id,
                                test_session_id=session_id,
                                # REMOVED: video_id=video.id,  # ❌ This field does not exist!
                                frame_number=frame_count,
                                timestamp=frame_count / fps,
                                confidence=detection.confidence,
                                class_label=detection.class_label,
                                # FIXED: Use correct column names
                                bounding_box_x=detection.bounding_box.x,
                                bounding_box_y=detection.bounding_box.y,
                                bounding_box_width=detection.bounding_box.width,
                                bounding_box_height=detection.bounding_box.height,
                                validation_result="VALIDATED",
                                # Optional: Add additional fields
                                detection_id=detection.detection_id,
                                vru_type=detection.class_label  # Map class_label to vru_type
                            )
                            db.add(detection_event)
