CREATE TABLE test_sessions (
	id VARCHAR(36) NOT NULL, 
	name VARCHAR NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	video_id VARCHAR(36) NOT NULL, 
	tolerance_ms INTEGER, 
	status VARCHAR, 
	session_type VARCHAR, 
	started_at DATETIME, 
	completed_at DATETIME, 
	created_at DATETIME DEFAULT (CURRENT_TIMESTAMP), 
	updated_at DATETIME, 
	has_video_sequence BOOLEAN, 
	sequence_id VARCHAR(36), 
	sequence_metadata JSON, 
	max_latency_threshold_ms FLOAT, 
	description TEXT, 
	latency_threshold_ms INTEGER, 
	video_start_timestamp FLOAT, 
	video_start_timestamp_ns VARCHAR, 
	precision_timing_enabled BOOLEAN, 
	timing_accuracy_ns FLOAT, 
	drift_compensation_active BOOLEAN, 
	frame_sync_enabled BOOLEAN, 
	sync_point_id VARCHAR, 
	calibration_timestamp FLOAT, 
	timing_validation_status VARCHAR, 
	hil_compliance_verified BOOLEAN, 
	video_playback_start_time FLOAT, 
	video_playback_start_time_ns VARCHAR, 
	hil_timing_enabled BOOLEAN, 
	video_timing_sync_status VARCHAR, 
	command_start_timestamp FLOAT, 
	command_start_timestamp_ns VARCHAR, 
	presentation_delay_ms FLOAT, 
	presentation_delay_ns VARCHAR, 
	presentation_delay_quality VARCHAR, failure_reason TEXT, failure_details JSON, failed_at DATETIME, retry_count INTEGER DEFAULT '0', last_retry_at DATETIME, approval_status VARCHAR(20) DEFAULT 'pending' NOT NULL, approved_by VARCHAR(255), approved_at DATETIME, approval_comments TEXT, rejection_reason TEXT, video_count INTEGER DEFAULT 1, video_sequences TEXT, current_video_index INTEGER DEFAULT 0, video_start_time FLOAT, completed_videos TEXT, pass_fail_result VARCHAR DEFAULT 'pending', overall_score FLOAT, accuracy_result VARCHAR DEFAULT 'pending', accuracy_f1_score FLOAT, accuracy_precision FLOAT, accuracy_recall FLOAT, accuracy_details JSON, latency_result VARCHAR DEFAULT 'pending', latency_mean_ms FLOAT, latency_max_ms FLOAT, latency_percent_within_threshold FLOAT, latency_details JSON, overall_test_result VARCHAR DEFAULT 'pending', overall_details JSON, tp_count INTEGER, fp_count INTEGER, fn_count INTEGER, test_configuration JSON, expected_detections INTEGER, actual_detections INTEGER, evaluation_details JSON, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(video_id) REFERENCES videos (id) ON DELETE CASCADE
)