
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vru_validation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/vru_validation
      - REDIS_URL=redis://redis:6379
      - API_PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - uploaded_videos:/app/uploads
    command: uvicorn main:socketio_app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped

  # CVAT for annotation (optional, can be deployed separately)
  cvat_db:
    image: postgres:15
    environment:
      POSTGRES_DB: cvat
      POSTGRES_USER: root
      POSTGRES_PASSWORD: cvat_password
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat:
    image: openvino/cvat_server:latest
    restart: always
    depends_on:
      - cvat_db
      - redis
    environment:
      CVAT_REDIS_HOST: redis
      CVAT_POSTGRES_HOST: cvat_db
      CVAT_POSTGRES_PASSWORD: cvat_password
      DJANGO_MODWSGI_EXTRA_ARGS: ""
    ports:
      - "8080:8080"
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs

volumes:
  postgres_data:
  redis_data:
  uploaded_videos:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

networks:
  default:
    name: vru_validation_network