
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vru_validation}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
    ports:
      - "${DATABASE_HOST:-127.0.0.1}:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_HOST:-127.0.0.1}:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-secure_redis_password}

  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "${BACKEND_HOST:-127.0.0.1}:8000:8000"
    environment:
      # Security
      - AIVALIDATION_SECRET_KEY=${AIVALIDATION_SECRET_KEY:-GENERATE_SECURE_KEY_FOR_PRODUCTION}
      # Database
      - AIVALIDATION_DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_password_change_me}@postgres:5432/${POSTGRES_DB:-vru_validation}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_password_change_me}@postgres:5432/${POSTGRES_DB:-vru_validation}
      # Redis
      - AIVALIDATION_REDIS_URL=redis://:${REDIS_PASSWORD:-secure_redis_password}@redis:6379
      # API Configuration
      - AIVALIDATION_API_PORT=8000
      - AIVALIDATION_API_HOST=0.0.0.0
      - AIVALIDATION_APP_ENVIRONMENT=${APP_ENV:-development}
      # Legacy support
      - API_PORT=8000
      - REDIS_URL=redis://:${REDIS_PASSWORD:-secure_redis_password}@redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - uploaded_videos:/app/uploads
    command: uvicorn main:socketio_app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_HOST:-127.0.0.1}:3000:3000"
    environment:
      - REACT_APP_API_URL=http://${BACKEND_HOST:-127.0.0.1}:8000
      - REACT_APP_WS_URL=ws://${BACKEND_HOST:-127.0.0.1}:8000
      - REACT_APP_SOCKETIO_URL=http://${BACKEND_HOST:-127.0.0.1}:8001
      - REACT_APP_VIDEO_BASE_URL=http://${BACKEND_HOST:-127.0.0.1}:8000
      - REACT_APP_ENVIRONMENT=${APP_ENV:-development}
      - REACT_APP_DEBUG=${REACT_DEBUG:-false}
      - REACT_APP_LOG_LEVEL=${REACT_LOG_LEVEL:-warning}
      - NODE_ENV=${NODE_ENV:-development}
      - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP:-false}
      - CI=true
      - DOCKER=true
      - NODE_OPTIONS=--max_old_space_size=4096
    depends_on:
      - backend
    restart: unless-stopped

  # CVAT for annotation (optional, can be deployed separately)
  cvat_db:
    image: postgres:15
    environment:
      POSTGRES_DB: cvat
      POSTGRES_USER: root
      POSTGRES_PASSWORD: cvat_password
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat:
    image: openvino/cvat_server:latest
    restart: always
    depends_on:
      - cvat_db
      - redis
    environment:
      CVAT_REDIS_HOST: redis
      CVAT_POSTGRES_HOST: cvat_db
      CVAT_POSTGRES_PASSWORD: cvat_password
      DJANGO_MODWSGI_EXTRA_ARGS: ""
    ports:
      - "155.138.239.131:8080:8080"
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs

volumes:
  postgres_data:
  redis_data:
  uploaded_videos:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

networks:
  default:
    name: vru_validation_network