services:
  alertmanager:
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    - --web.external-url=http://localhost:9093
    container_name: alertmanager
    image: prom/alertmanager:latest
    ports:
    - 9093:9093
    restart: unless-stopped
    volumes:
    - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    - alertmanager_data:/alertmanager
  grafana:
    container_name: grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=performance_admin
    - GF_INSTALL_PLUGINS=grafana-piechart-panel
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
  node-exporter:
    command:
    - --path.procfs=/host/proc
    - --path.rootfs=/rootfs
    - --path.sysfs=/host/sys
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
    - 9100:9100
    restart: unless-stopped
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
  postgres-exporter:
    container_name: postgres-exporter
    environment:
    - DATA_SOURCE_NAME=postgresql://username:password@postgres:5432/database?sslmode=disable
    image: prometheuscommunity/postgres-exporter:latest
    ports:
    - 9187:9187
    restart: unless-stopped
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --storage.tsdb.retention.time=200h
    - --web.enable-lifecycle
    - --web.enable-admin-api
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    - prometheus_data:/prometheus
version: '3.8'
volumes:
  alertmanager_data: {}
  grafana_data: {}
  prometheus_data: {}
