alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- alert_rules.yml
scrape_configs:
- job_name: api-server
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - api:8001
- job_name: frontend-vitals
  metrics_path: /api/metrics/vitals
  static_configs:
  - targets:
    - frontend:3000
- job_name: database
  static_configs:
  - targets:
    - postgres-exporter:9187
- job_name: system-metrics
  static_configs:
  - targets:
    - node-exporter:9100
