# VRU Production Prometheus Configuration
# Monitoring and metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vru-production'
    replica: 'prometheus-01'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # API Gateway monitoring
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # ML Engine monitoring
  - job_name: 'ml-engine'
    static_configs:
      - targets: ['ml-engine:8001']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 15s

  # Camera Service monitoring
  - job_name: 'camera-service'
    static_configs:
      - targets: ['camera-service:8002']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Validation Engine monitoring
  - job_name: 'validation-engine'
    static_configs:
      - targets: ['validation-engine:8003']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 15s

  # Frontend monitoring (if metrics endpoint available)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 60s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']  # nginx-prometheus-exporter
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']  # redis_exporter
    scrape_interval: 30s

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']  # postgres_exporter
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['155.138.239.131:9100']
    scrape_interval: 30s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB