#!/usr/bin/env python3
"""
Database cleanup script to remove phantom "Detection Session" entries.
These are auto-generated test sessions that clutter the UI without providing user value.
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy.orm import Session
from sqlalchemy import and_, or_
from datetime import datetime, timedelta
import logging

from database import SessionLocal, engine
from models import TestSession, DetectionEvent

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def cleanup_phantom_sessions(dry_run=True):
    """
    Remove phantom detection sessions that were auto-generated by the detection pipeline.
    
    Args:
        dry_run (bool): If True, only show what would be deleted without actually deleting
    """
    db = SessionLocal()
    try:
        logger.info("🔍 Starting phantom session cleanup...")
        
        # Find phantom sessions with the detection pipeline naming pattern
        phantom_sessions = db.query(TestSession).filter(
            or_(
                TestSession.name.like("Detection Session - %"),
                TestSession.name.like("Detection Session%"),
                and_(
                    TestSession.name.contains("Detection"),
                    TestSession.name.contains("Session"),
                    TestSession.status == "completed"
                )
            )
        ).all()
        
        logger.info(f"Found {len(phantom_sessions)} phantom sessions")
        
        # Log details of what we found
        for session in phantom_sessions:
            detection_count = db.query(DetectionEvent).filter(
                DetectionEvent.test_session_id == session.id
            ).count()
            
            logger.info(f"  📋 Session: '{session.name}' (ID: {session.id[:8]}...)")
            logger.info(f"     Created: {session.created_at}")
            logger.info(f"     Status: {session.status}")
            logger.info(f"     Detections: {detection_count}")
            
        if dry_run:
            logger.info("🚫 DRY RUN MODE - No sessions will be deleted")
            logger.info("Run with dry_run=False to actually delete phantom sessions")
        else:
            # Delete phantom sessions (cascade will delete related detection events)
            deleted_count = 0
            for session in phantom_sessions:
                try:
                    # Get detection count for logging
                    detection_count = db.query(DetectionEvent).filter(
                        DetectionEvent.test_session_id == session.id
                    ).count()
                    
                    # Delete the session (cascade deletes related detection events)
                    db.delete(session)
                    deleted_count += 1
                    
                    logger.info(f"🗑️  Deleted phantom session '{session.name}' and {detection_count} detection events")
                    
                except Exception as e:
                    logger.error(f"❌ Error deleting session {session.id}: {e}")
                    continue
            
            # Commit all deletions
            db.commit()
            logger.info(f"✅ Successfully deleted {deleted_count} phantom sessions")
            
    except Exception as e:
        db.rollback()
        logger.error(f"❌ Error during cleanup: {e}")
        raise
    finally:
        db.close()

def cleanup_old_detection_sessions(days_old=7, dry_run=True):
    """
    Remove old detection sessions that are older than specified days.
    
    Args:
        days_old (int): Remove sessions older than this many days
        dry_run (bool): If True, only show what would be deleted
    """
    db = SessionLocal()
    try:
        cutoff_date = datetime.utcnow() - timedelta(days=days_old)
        
        old_sessions = db.query(TestSession).filter(
            and_(
                or_(
                    TestSession.name.like("Detection Session - %"),
                    TestSession.name.like("Detection Session%")
                ),
                TestSession.created_at < cutoff_date
            )
        ).all()
        
        logger.info(f"Found {len(old_sessions)} old detection sessions (older than {days_old} days)")
        
        if dry_run:
            for session in old_sessions:
                logger.info(f"  Would delete: '{session.name}' from {session.created_at}")
            logger.info("🚫 DRY RUN MODE - No old sessions will be deleted")
        else:
            deleted_count = 0
            for session in old_sessions:
                try:
                    db.delete(session)
                    deleted_count += 1
                    logger.info(f"🗑️  Deleted old session: '{session.name}'")
                except Exception as e:
                    logger.error(f"❌ Error deleting old session {session.id}: {e}")
                    continue
            
            db.commit()
            logger.info(f"✅ Successfully deleted {deleted_count} old detection sessions")
            
    except Exception as e:
        db.rollback()
        logger.error(f"❌ Error during old session cleanup: {e}")
        raise
    finally:
        db.close()

def get_session_stats():
    """Get statistics about test sessions in the database."""
    db = SessionLocal()
    try:
        total_sessions = db.query(TestSession).count()
        phantom_sessions = db.query(TestSession).filter(
            or_(
                TestSession.name.like("Detection Session - %"),
                TestSession.name.like("Detection Session%")
            )
        ).count()
        
        legitimate_sessions = total_sessions - phantom_sessions
        
        logger.info("📊 Session Statistics:")
        logger.info(f"  Total sessions: {total_sessions}")
        logger.info(f"  Phantom sessions: {phantom_sessions}")
        logger.info(f"  Legitimate sessions: {legitimate_sessions}")
        
        return {
            "total": total_sessions,
            "phantom": phantom_sessions,
            "legitimate": legitimate_sessions
        }
        
    finally:
        db.close()

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Clean up phantom detection sessions")
    parser.add_argument("--execute", action="store_true", help="Actually delete sessions (default is dry run)")
    parser.add_argument("--days", type=int, default=7, help="Delete sessions older than N days (default: 7)")
    parser.add_argument("--stats-only", action="store_true", help="Only show statistics, don't delete anything")
    
    args = parser.parse_args()
    
    if args.stats_only:
        get_session_stats()
    else:
        dry_run = not args.execute
        
        logger.info("🧹 AI Model Validation Platform - Phantom Session Cleanup")
        logger.info(f"Mode: {'EXECUTE' if args.execute else 'DRY RUN'}")
        
        # Show current statistics
        get_session_stats()
        
        # Clean up phantom sessions
        cleanup_phantom_sessions(dry_run=dry_run)
        
        # Clean up old sessions
        cleanup_old_detection_sessions(days_old=args.days, dry_run=dry_run)
        
        if not args.execute:
            logger.info("🔧 To actually delete phantom sessions, run:")
            logger.info("python scripts/cleanup_phantom_sessions.py --execute")